### ISSUE TITLE
Paper theme headings have no default font-family

### ISSUE THREAD

**Issue by olizilla** [itajaja/markdawn#10]
https://github.com/itajaja/markdawn/blob/master/themes/paper/style.css#L254

This falls back to a default serif font on any system where Calibri isn't available.

**Comment by itajaja** [comment]
Thanks Oli! Are you on a *nix machine right? I unfortunately could test it only on windows at that time, now that I have a mac I should take this project again, because I think that phantomjs has a completely different behavior on windows and unix when it comes to rendering to pdf. I just pushed [an example folder](https://github.com/itajaja/markdawn/tree/master/examples), if you want to compare the outputs with a windows version. I am gonna check it as soon as I get back to my mac later tonight

**Comment by olizilla** [comment]
:smile_cat: 
Kind of, I'm on osx. It may not be a problem in the rendered pdf, just something I spotted while checking an html preview.

In the example folder, https://raw.githubusercontent.com/itajaja/markdawn/master/examples/default.pdf fails for me. The manuscript.pdf looks good.

**Comment by itajaja** [comment]
ops, that pdf file was not supposed to be there. I uploaded the correct one, thanks for noticing
